# Generated by Django 3.0.8 on 2020-07-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_member', models.CharField(max_length=50, verbose_name='nome')),
                ('name_mother', models.CharField(max_length=50, verbose_name='nome mãe')),
                ('name_father', models.CharField(max_length=50, verbose_name='nome pai')),
                ('natural_from', models.CharField(max_length=50, verbose_name='natural de')),
                ('marital_status', models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widower', 'Viúvo(a)'), ('separate', 'Separado(a)')], max_length=10, verbose_name='estado civil')),
                ('doc_id', models.CharField(max_length=10, verbose_name='RG')),
                ('birth_dt', models.DateField(verbose_name='data de nascimento')),
                ('member_since_dt', models.DateField(verbose_name='membro desde')),
                ('baptism_dt', models.DateField(verbose_name='data de batismo')),
                ('address', models.CharField(max_length=200, verbose_name='endereço')),
                ('valid', models.IntegerField(verbose_name='validade')),
            ],
            options={
                'verbose_name': 'membro',
                'verbose_name_plural': 'membros',
            },
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'pastor',
                'verbose_name_plural': 'pastores',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='numero')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
            options={
                'verbose_name': 'telefone',
                'verbose_name_plural': 'telefones',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='minister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Minister', verbose_name='Pastor'),
        ),
    ]
